### ISSUE TITLE
Adriana Gonzalez Braniff Resume CSS

### ISSUE THREAD

**Issue by Adrianagb** [umiami-web-design/css#5]
https://adrianagb.github.io/resume.html

:)

**Comment by ebrown15** [comment]
Grade is in CaneLink. Great job!

**Comment by Adrianagb** [comment]
Thanks professor!

Where on canelink? I cant find it!

P.s. Did you get my photo of my desktop for the class?

Best,
Adriana

Sent from my iPhone

On Nov 30, 2017, at 8:40 PM, Erin Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


Grade is in CaneLink. Great job!
